#service: serverless-apollo-template

provider:
  name: aws
  runtime: nodejs10.x
  logs:
    restApi: true
#  iamRoleStatements:
#    - Effect: 'Allow'
#      Action:
#        - 'dynamodb:Query'
#      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/towbe_job_request

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-include-dependencies
  - serverless-webpack
  - serverless-pseudo-parameters
  - serverless-plugin-ifelse

functions:
  hello:
    handler: src/gql/handler.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
