service: serverless-apollo-template

provider:
  name: aws
  runtime: nodejs10.x
  logs:
    restApi: true

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-include-dependencies
  - serverless-webpack
  - serverless-pseudo-parameters

functions:
  hello:
    handler: src/gql/handler.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
