version: 2.1

jobs:
  build:
    docker:
      - image: node:12
    environment:
      NODE_ENV: production
    steps:
      - checkout
      - run: mv .npmrc-ci .npmrc
      - run: npm ci
      - run: npm run deploy

  test:
    docker:
      - image: node:12
    environment:
      NODE_ENV: production
    steps:
      - checkout
      - run: mv .npmrc-ci .npmrc
      - run: npm ci

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: awscreds
          filters:
            branches:
              only:
                - master
  test:
    jobs:
      - test:
          context: npm-dep
          filters:
            branches:
              ignore:
                - master