version: 2.1

jobs:
  build:
    docker:
      - image: node:12
    steps:
      - checkout
      - run: npm ci
      - run: sls deploy

  test:
    docker:
      - image: node:12
    steps:
      - checkout
      - run: npm ci

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: org-global
          filters:
            branches:
              only:
                - master
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master