version: 2.1

jobs:
  build:
    steps:
      - checkout
      - run: npm ci
      - run: sls deploy

  test:
    steps:
      - checkout
      - run: npm ci

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: org-global